server:
  port: 8080

spring:
  application:
    name: gateway

aic:
  auth-service:
    url: ${AUTH_SERVICE_URL:http://localhost:8081}
  orders-service:
    url: ${ORDERS_SERVICE_URL:http://localhost:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
